version: 1
formatters:
  default:
    (): formatters.HostnameFormatter
    format: '%(levelname)s %(asctime)s - id:[%(hostname)s] - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: default
    filename: logs/app.log
    encoding: utf8
loggers:
  uvicorn:
    handlers: [console, file]
    level: INFO
    propagate: false
  uvicorn.error:
    handlers: [console, file]
    level: ERROR
    propagate: false
  uvicorn.access:
    handlers: [console, file]
    level: INFO
    propagate: false
root:
  handlers: [console, file]
  level: INFO
